#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.
if [[ $# == 1 ]]
then
        sudo mysqldump -u root --password="$1" -A > backup.sql
        filename=$(date +"%d-%m-%y")
        sudo tar -zcvf "$filename".tar.gz backup.sql
fi
