#!/usr/bin/env bash
# Installs ufw firewall and set-up a few rules
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
echo 'y' | sudo ufw enable
