#!/usr/bin/env bash
#Configures new hosts for local machine
sudo cp /etc/hosts /etc/hosts.old
cp /etc/hosts ~/hosts.new
chmod a+w ~/hosts.new
sed -i 's/^127.[0-9].[0-9].[0-9]/127.0.0.2/' ~/hosts.new
printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new
sudo cp ~/hosts.new /etc/hosts
rm ~/hosts.new
