#!/usr/bin/env bash
#Configures new hosts for local machine
cp /etc/hosts ~/hosts.new
chmod a+w ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new
sudo cp ~/hosts.new /etc/hosts
