#!/usr/bin/env bash
#Configures new hosts for local machine
sudo cp /etc/hosts /etc/hosts.old
cp /etc/hosts ~/hosts.new
chmod a+w ~/hosts.new
sed -i 's/^127.*$/127.0.0.2 localhost/' ~/hosts.new
printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new
sudo cp ~/hosts.new /etc/hosts
sudo rm ~/hosts.new
